const devices = [
  {id:'macbook-air-m4',category:'laptops',score:98,name:'MacBook Air M4',brand:'Apple',price:24999,year:2025,feature:'Batería y rendimiento',image:'img/macbook-air-m4.svg',colors:['Medianoche','Blanco estrella','Plata','Azul cielo'],processorVersions:['Apple M4 8-core CPU','Apple M4 10-core GPU'],ramVersions:['16 GB','24 GB','32 GB'],storageVersions:['256 GB','512 GB','1 TB','2 TB'],highlights:['Apple M4','Hasta 18 h','Liquid Retina'],quick:['13.6”','16-32GB','256GB-2TB','18 h'],specs:{Pantalla:'13.6” Liquid Retina',Procesador:'Apple M4',GPU:'8/10 núcleos',RAM:'16, 24 o 32 GB',Almacenamiento:'256 GB a 2 TB SSD',Batería:'Hasta 18 horas',Peso:'1.24 kg',Sistema:'macOS'},pros:['Muy ligera','Excelente batería','Silenciosa y rápida'],cons:['Pocos puertos','No es para gaming pesado'],recommended:'Estudiantes, programación, oficina, edición ligera y uso diario.'},
  {id:'rog-g14',category:'laptops',score:95,name:'ROG Zephyrus G14',brand:'ASUS',price:38999,year:2024,feature:'Gaming y edición',image:'img/rog-g14.svg',colors:['Eclipse Gray','Platinum White'],processorVersions:['Ryzen 9 8945HS','Ryzen 7'],ramVersions:['16 GB','32 GB'],storageVersions:['1 TB SSD','2 TB SSD'],highlights:['Ryzen 9','RTX 4060/4070','OLED 120 Hz'],quick:['14” OLED','16-32GB','RTX 4070','1.5 kg'],specs:{Pantalla:'14” OLED 120 Hz',Procesador:'AMD Ryzen 9',GPU:'RTX 4060 / RTX 4070',RAM:'16/32 GB',Almacenamiento:'1 TB / 2 TB SSD',Batería:'Buena para su potencia',Peso:'1.5 kg',Sistema:'Windows 11'},pros:['Muy potente','Pantalla premium','Compacta'],cons:['Puede calentarse','Precio alto'],recommended:'Gaming, diseño 3D, edición de video y tareas pesadas.'},
  {id:'dell-xps-13',category:'laptops',score:91,name:'Dell XPS 13',brand:'Dell',price:27999,year:2024,feature:'Trabajo premium',image:'img/dell-xps.svg',colors:['Graphite','Platinum'],processorVersions:['Intel Core Ultra 5','Intel Core Ultra 7'],ramVersions:['16 GB','32 GB'],storageVersions:['512 GB','1 TB','2 TB'],highlights:['Core Ultra','OLED opcional','Diseño premium'],quick:['13.4”','16-32GB','Core Ultra','1.2 kg'],specs:{Pantalla:'13.4” FHD+/OLED',Procesador:'Intel Core Ultra',GPU:'Intel Arc integrada',RAM:'16/32 GB',Almacenamiento:'512 GB a 2 TB SSD',Batería:'Hasta 15 h aprox.',Peso:'1.2 kg',Sistema:'Windows 11'},pros:['Diseño elegante','Buena pantalla','Excelente teclado'],cons:['Puertos limitados','Reparación compleja'],recommended:'Trabajo profesional, universidad, oficina y viajes.'},
  {id:'airpods-pro-2',category:'audifonos',score:97,name:'AirPods Pro 2',brand:'Apple',price:4999,year:2023,feature:'Cancelación de ruido',image:'img/airpods-pro.svg',colors:['White'],versions:['USB-C','Lightning'],batteryVersions:['Hasta 6 h audífonos','Hasta 30 h con estuche'],highlights:['ANC avanzado','Modo ambiente','Audio espacial'],quick:['ANC','30 h','IP54','USB-C'],specs:{Tipo:'In-ear',Cancelación:'ANC adaptativa',Batería:'Hasta 30 h con estuche',Micrófono:'Muy bueno',Resistencia:'IP54',Compatibilidad:'iPhone, iPad, Mac y Android básico',Carga:'USB-C / MagSafe'},pros:['Excelente ANC','Muy cómodos','Integración Apple'],cons:['Más completos en Apple','Precio alto'],recommended:'iPhone, Mac, llamadas, viajes y contenido.'},
  {id:'beats-buds-plus',category:'audifonos',score:89,name:'Beats Studio Buds+',brand:'Beats',price:3299,year:2023,feature:'Bajos y compatibilidad',image:'img/beats-buds.svg',colors:['Transparent','Black','Ivory','Cosmic Pink'],versions:['Studio Buds+'],batteryVersions:['Hasta 9 h audífonos','Hasta 36 h con estuche'],highlights:['36 h batería','ANC','iOS y Android'],quick:['ANC','36 h','IPX4','USB-C'],specs:{Tipo:'Earbuds',Cancelación:'ANC y transparencia',Batería:'Hasta 36 h con estuche',Micrófono:'Bueno',Resistencia:'IPX4',Compatibilidad:'iOS y Android',Carga:'USB-C'},pros:['Bajos fuertes','Buena batería','Buen soporte Android'],cons:['ANC menor que AirPods','Sin carga inalámbrica'],recommended:'Música urbana, gimnasio, uso diario y Android/iPhone.'},
  {id:'sony-xm5',category:'audifonos',score:96,name:'Sony WH-1000XM5',brand:'Sony',price:6999,year:2022,feature:'Audio premium',image:'img/sony-xm5.svg',colors:['Black','Silver','Midnight Blue'],versions:['WH-1000XM5'],batteryVersions:['Hasta 30 h ANC','Carga rápida'],highlights:['ANC top','LDAC','Over-ear'],quick:['Over-ear','30 h','LDAC','ANC top'],specs:{Tipo:'Over-ear',Cancelación:'Excelente',Batería:'Hasta 30 h',Micrófono:'Muy bueno',Códecs:'SBC, AAC, LDAC',Compatibilidad:'Universal',Carga:'USB-C'},pros:['Sonido premium','Cancelación excelente','Muy cómodos'],cons:['Grandes','No son para lluvia'],recommended:'Viajes, oficina, concentración y audio de alta calidad.'},
  {id:'iphone-16-pro',category:'telefonos',score:98,name:'iPhone 16 Pro',brand:'Apple',price:25999,year:2024,feature:'Cámara y video',image:'img/iphone-16-pro.svg',colors:['Black Titanium','White Titanium','Natural Titanium','Desert Titanium'],processorVersions:['A18 Pro'],ramVersions:['8 GB aprox.'],storageVersions:['128 GB','256 GB','512 GB','1 TB'],highlights:['A18 Pro','48 MP','Titanio'],quick:['6.3”','A18 Pro','48 MP','1 TB'],specs:{Pantalla:'6.3” OLED ProMotion',Procesador:'A18 Pro',RAM:'8 GB aprox.',Almacenamiento:'128 GB a 1 TB',Cámara:'Sistema Pro 48 MP',Batería:'Alta duración',Sistema:'iOS',Carga:'USB-C'},pros:['Video excelente','Rendimiento brutal','Material premium'],cons:['Caro','Carga no tan rápida'],recommended:'Creadores de contenido, video, fotos y ecosistema Apple.'},
  {id:'galaxy-s25',category:'telefonos',score:96,name:'Galaxy S25',brand:'Samsung',price:22999,year:2025,feature:'Pantalla e IA',image:'img/galaxy-s25.svg',colors:['Icy Blue','Mint','Navy','Silver Shadow'],processorVersions:['Snapdragon 8 Elite','Exynos según región'],ramVersions:['12 GB'],storageVersions:['128 GB','256 GB','512 GB'],highlights:['AMOLED','IA integrada','Triple cámara'],quick:['6.2”','12GB','AMOLED','IA'],specs:{Pantalla:'Dynamic AMOLED 120 Hz',Procesador:'Snapdragon/Exynos',RAM:'12 GB',Almacenamiento:'128/256/512 GB',Cámara:'Triple cámara',Batería:'Carga rápida',Sistema:'Android / One UI',Carga:'USB-C'},pros:['Pantalla brillante','Funciones IA','Muy completo'],cons:['Apps duplicadas','Precio alto'],recommended:'Android premium, productividad, pantalla y fotografía.'},
  {id:'pixel-9-pro',category:'telefonos',score:94,name:'Pixel 9 Pro',brand:'Google',price:21999,year:2024,feature:'Fotografía IA',image:'img/pixel-9-pro.svg',colors:['Obsidian','Porcelain','Hazel','Rose Quartz'],processorVersions:['Google Tensor G4'],ramVersions:['16 GB'],storageVersions:['128 GB','256 GB','512 GB','1 TB'],highlights:['Cámara IA','Android limpio','OLED 120 Hz'],quick:['OLED','16GB','Tensor G4','IA'],specs:{Pantalla:'OLED 120 Hz',Procesador:'Google Tensor G4',RAM:'16 GB',Almacenamiento:'128 GB a 1 TB',Cámara:'IA avanzada',Batería:'Todo el día',Sistema:'Android puro',Carga:'USB-C'},pros:['Fotos excelentes','Android limpio','Funciones IA'],cons:['Disponibilidad variable','Carga mejorable'],recommended:'Fotografía, Android puro y herramientas inteligentes.'}
];

const news = [
  {title:'Compra con cabeza',text:'No te vayas solo por el precio: revisa actualizaciones, batería, garantía y versiones disponibles.'},
  {title:'Elige según tu uso',text:'Una laptop para escuela no necesita lo mismo que una para edición o gaming. Filtra por lo que realmente harás.'},
  {title:'Comparar ayuda mucho',text:'La vista VS te enseña diferencias de pantalla, batería, memoria, cámara, colores y ventajas.'}
];
const categoryInfo={laptops:{title:'Laptops',eyebrow:'💻 Comparación de laptops',description:'Portátiles para escuela, programación, diseño, trabajo y gaming.',chips:['Procesador','RAM','SSD','Batería','GPU']},audifonos:{title:'Audífonos',eyebrow:'🎧 Comparación de audífonos',description:'Modelos con cancelación, batería, micrófono, códecs y compatibilidad.',chips:['ANC','Batería','Micrófono','Códecs','Resistencia']},telefonos:{title:'Celulares',eyebrow:'📱 Comparación de celulares',description:'Smartphones con cámara, pantalla, RAM, almacenamiento, carga y colores.',chips:['Cámara','Pantalla','RAM','Batería','IA']}};
const state={category:'laptops',compare:[],lastView:'home'};
const $=s=>document.querySelector(s);
const $$=s=>document.querySelectorAll(s);
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
const join=a=>Array.isArray(a)&&a.length?a.join(', '):'No especificado';
function icon(name){
  const icons={
    screen:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="12" rx="2"/><path d="M8 21h8M12 17v4"/></svg>',
    chip:'<svg viewBox="0 0 24 24"><rect x="7" y="7" width="10" height="10" rx="2"/><path d="M4 9h3M4 15h3M17 9h3M17 15h3M9 4v3M15 4v3M9 17v3M15 17v3"/></svg>',
    drive:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="14" rx="3"/><path d="M8 15h8M8 9h2"/></svg>',
    battery:'<svg viewBox="0 0 24 24"><rect x="3" y="8" width="16" height="8" rx="2"/><path d="M21 11v2M7 12h6"/></svg>',
    headphones:'<svg viewBox="0 0 24 24"><path d="M4 13a8 8 0 0 1 16 0"/><rect x="3" y="13" width="4" height="7" rx="2"/><rect x="17" y="13" width="4" height="7" rx="2"/></svg>',
    noise:'<svg viewBox="0 0 24 24"><path d="M4 12h3l4-4v8l-4-4H4zM17 9l4 6M21 9l-4 6"/></svg>',
    drop:'<svg viewBox="0 0 24 24"><path d="M12 3s6 6.2 6 10a6 6 0 0 1-12 0c0-3.8 6-10 6-10z"/></svg>',
    phone:'<svg viewBox="0 0 24 24"><rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 18h2"/></svg>',
    camera:'<svg viewBox="0 0 24 24"><path d="M5 7h3l1.5-2h5L16 7h3a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2z"/><circle cx="12" cy="13" r="3"/></svg>',
    bolt:'<svg viewBox="0 0 24 24"><path d="M13 2 4 14h7l-1 8 10-13h-7l0-7z"/></svg>',
    palette:'<svg viewBox="0 0 24 24"><path d="M12 3a9 9 0 0 0 0 18h1.5a2 2 0 0 0 1-3.73A2 2 0 0 1 15.5 14H17a4 4 0 0 0 0-8h-1.5A8.9 8.9 0 0 0 12 3z"/><circle cx="7.5" cy="11" r=".7"/><circle cx="10" cy="7.5" r=".7"/><circle cx="14" cy="7.5" r=".7"/></svg>',
    star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.8 1-6.1-4.4-4.3 6.1-.9L12 3z"/></svg>',
    check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',
    alert:'<svg viewBox="0 0 24 24"><path d="M12 3 2 21h20L12 3z"/><path d="M12 9v5M12 17h.01"/></svg>',
    link:'<svg viewBox="0 0 24 24"><path d="M10 13a5 5 0 0 0 7 0l2-2a5 5 0 0 0-7-7l-1 1"/><path d="M14 11a5 5 0 0 0-7 0l-2 2a5 5 0 0 0 7 7l1-1"/></svg>',
    music:'<svg viewBox="0 0 24 24"><path d="M9 18V5l10-2v13"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="16" r="2"/></svg>',
    weight:'<svg viewBox="0 0 24 24"><path d="M7 8h10l2 13H5L7 8z"/><path d="M9 8a3 3 0 0 1 6 0"/></svg>',
    gear:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 12h2M3 12h2M12 3v2M12 19v2M17 7l1.5-1.5M5.5 18.5 7 17M7 7 5.5 5.5M18.5 18.5 17 17"/></svg>',
    plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
    compare:'<svg viewBox="0 0 24 24"><path d="M7 7h11M7 7l3-3M7 7l3 3M17 17H6M17 17l-3-3M17 17l-3 3"/></svg>'
  };
  return '<span class="mini-icon" aria-hidden="true">'+(icons[name]||icons.star)+'</span>';
}
const iconSet={laptops:['screen','chip','drive','battery'],audifonos:['headphones','noise','battery','drop'],telefonos:['phone','bolt','camera','chip']};
function quickIcons(d){return iconSet[d.category]||['star','star','star','star'];}
function versionTitle(d){return d.category==='audifonos'?'Modelo, sonido y batería':'Procesador, memoria y versiones';}
function versionBlocks(d){
  if(d.category==='audifonos') return [{icon:'headphones',label:'Versiones',value:join(d.versions)},{icon:'battery',label:'Batería',value:join(d.batteryVersions)},{icon:'palette',label:'Colores',value:join(d.colors)}];
  return [{icon:'chip',label:'Procesadores',value:join(d.processorVersions)},{icon:'drive',label:'RAM',value:join(d.ramVersions)},{icon:'drive',label:'Almacenamiento',value:join(d.storageVersions)}];
}
function specIcon(key){const map={Pantalla:'screen',Procesador:'chip',GPU:'bolt',RAM:'drive',Almacenamiento:'drive',Batería:'battery',Peso:'weight',Sistema:'gear',Tipo:'headphones',Cancelación:'noise',Micrófono:'music',Resistencia:'drop',Compatibilidad:'link',Carga:'bolt',Códecs:'music',Cámara:'camera'};return icon(map[key]||'star');}
function renderNews(){ $('#newsGrid').innerHTML=news.map(n=>`<article class="news-card"><h3>${n.title}</h3><p>${n.text}</p></article>`).join(''); }
function hideAll(){ $$('[data-page="home"]').forEach(e=>e.classList.add('hidden')); $('#catalogo').classList.add('hidden'); $('#detailPage').classList.add('hidden'); $('#comparePage').classList.add('hidden'); }
function showHome(){ hideAll(); $$('[data-page="home"]').forEach(e=>e.classList.remove('hidden')); state.lastView='home'; setActive('home'); }
function setActive(v){ $$('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.category===v||a.dataset.view===v)); }
function showCategory(category){ hideAll(); state.category=category; $('#catalogo').classList.remove('hidden'); const info=categoryInfo[category]; $('#categoryEyebrow').textContent=info.eyebrow; $('#categoryTitle').textContent=info.title; $('#categoryDescription').textContent=info.description; $('#categoryChips').innerHTML=info.chips.map(c=>`<span>${c}</span>`).join(''); $('#productsTitle').textContent=`${info.title} disponibles`; setupFilters(); renderProducts(); state.lastView='catalog'; setActive(category); window.scrollTo({top:0,behavior:'smooth'}); }
function setupFilters(){const data=devices.filter(d=>d.category===state.category); const brands=['Todas',...new Set(data.map(d=>d.brand))]; const years=['Todos',...new Set(data.map(d=>d.year).sort((a,b)=>b-a))]; const features=['Todas',...new Set(data.map(d=>d.feature))]; $('#searchInput').value=''; $('#brandFilter').innerHTML=brands.map(b=>`<option>${b}</option>`).join(''); $('#yearFilter').innerHTML=years.map(y=>`<option>${y}</option>`).join(''); $('#featureFilter').innerHTML=features.map(f=>`<option>${f}</option>`).join(''); const max=Math.ceil(Math.max(...data.map(d=>d.price))/500)*500; $('#priceRange').max=max; $('#priceRange').value=max; updatePriceLabel();}
function updatePriceLabel(){ $('#priceValue').textContent=`Hasta ${money(Number($('#priceRange').value))}`; }
function filtered(){const q=$('#searchInput').value.toLowerCase().trim();return devices.filter(d=>d.category===state.category).filter(d=>!q||`${d.name} ${d.brand} ${d.feature} ${d.recommended}`.toLowerCase().includes(q)).filter(d=>$('#brandFilter').value==='Todas'||d.brand===$('#brandFilter').value).filter(d=>$('#yearFilter').value==='Todos'||d.year>=Number($('#yearFilter').value)).filter(d=>$('#featureFilter').value==='Todas'||d.feature===$('#featureFilter').value).filter(d=>d.price<=Number($('#priceRange').value));}
function renderProducts(){const data=filtered(); $('#resultCount').textContent=`${data.length} resultado${data.length===1?'':'s'}`; $('#productsGrid').innerHTML=data.map(d=>{const selected=state.compare.includes(d.id);return `<article class="product-card ${selected?'selected':''}" data-product="${d.id}"><div class="score"><b>${d.score}</b><small>pts</small></div><div class="product-img"><img src="${d.image}" alt="${d.name}" loading="lazy"></div><div class="product-info"><div class="product-topline"><span>${d.brand}</span><span>${d.year}</span></div><h3>${d.name}</h3><div class="price">${money(d.price)}</div><p class="product-meta">${d.feature} · ${d.recommended}</p><div class="spec-icons">${d.quick.map((q,i)=>`<span>${icon(quickIcons(d)[i])}<strong>${q}</strong></span>`).join('')}</div><div class="card-actions"><button class="details-btn" data-details="${d.id}" type="button">Ver ficha completa</button><button class="small-btn compare-action" data-compare="${d.id}" type="button">${selected?'✓ En VS':'Agregar a VS'}</button></div></div><button class="plus-btn ${selected?'active':''}" data-compare="${d.id}" type="button">${selected?'✓':'+'}</button></article>`}).join('')||'<p class="empty-results">No hay productos con esos filtros.</p>';}
function showDetail(id){const d=devices.find(x=>x.id===id); if(!d)return; hideAll(); $('#detailPage').classList.remove('hidden'); const blocks=versionBlocks(d); $('#detailContent').innerHTML=`<div class="detail-hero pro-detail"><div class="detail-image"><div class="detail-glow"></div><img src="${d.image}" alt="${d.name}"></div><div class="detail-info"><p class="eyebrow">${d.brand} · ${d.year} · ${d.feature}</p><h2>${d.name}</h2><div class="detail-price-row"><div class="price">${money(d.price)}</div><span class="detail-score">${icon('star')} ${d.score} puntos</span></div><p class="detail-summary">${d.recommended}</p><div class="detail-highlights">${d.highlights.map(h=>`<span>${icon('star')} ${h}</span>`).join('')}</div><div class="card-actions"><button class="small-btn compare-action" data-compare="${d.id}" type="button">Agregar al comparador</button></div></div></div><div class="detail-stats">${blocks.map(b=>`<article><strong>${icon(b.icon)}</strong><span>${b.label}</span><p>${b.value}</p></article>`).join('')}</div><div class="wow-strip"><article><span>${icon('star')}</span><div><b>Lo más chido</b><p>${d.highlights.join(' · ')}</p></div></article><article><span>${icon('check')}</span><div><b>Ideal para</b><p>${d.recommended}</p></div></article><article><span>${icon('compare')}</span><div><b>Compra inteligente</b><p>Revisa versiones, colores y limitaciones antes de compararlo.</p></div></article></div><div class="detail-grid enhanced"><div class="detail-box colors-box"><h3>${icon('palette')} Colores disponibles</h3><div class="pill-list color-pills">${d.colors.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="detail-box"><h3>${icon('chip')} ${versionTitle(d)}</h3>${blocks.map(b=>`<p><b>${icon(b.icon)} ${b.label}:</b> ${b.value}</p>`).join('')}</div><div class="detail-box good"><h3>${icon('check')} Ventajas</h3>${d.pros.map(x=>`<p>${icon('check')} ${x}</p>`).join('')}</div><div class="detail-box bad"><h3>${icon('alert')} Puntos a considerar</h3>${d.cons.map(x=>`<p>${icon('alert')} ${x}</p>`).join('')}</div></div><div class="detail-box spec-panel"><h3>${icon('compare')} Especificaciones completas</h3><div class="spec-card-grid">${Object.entries(d.specs).map(([k,v])=>`<article><span>${specIcon(k)}</span><div><b>${k}</b><p>${v}</p></div></article>`).join('')}</div></div>`; window.scrollTo({top:0,behavior:'smooth'});}
function renderProductsIfVisible(){ if(!$('#catalogo').classList.contains('hidden')) renderProducts(); }
function addCompare(id){ if(!state.compare.includes(id)){ if(state.compare.length>=3){ alert('Puedes comparar máximo 3 productos.'); return;} state.compare.push(id);} renderDrawer(); renderProductsIfVisible();}
function removeCompare(id){state.compare=state.compare.filter(x=>x!==id);renderDrawer();renderProductsIfVisible();}
function renderDrawer(){
  const list=state.compare.map(id=>devices.find(d=>d.id===id)).filter(Boolean);
  const drawer=$('#compareDrawer');
  drawer.classList.toggle('is-active',list.length>0);
  const remaining=Math.max(0,3-list.length);
  $('#drawerBody').innerHTML=list.length?
    '<div class="drawer-progress"><span>'+list.length+'/3 seleccionados</span><small>'+ (list.length<2?'Falta 1 para comparar':'Listo para comparar') +'</small></div>'+list.map((d,index)=>
      '<div class="drawer-item pro-drawer-item"><img src="'+d.image+'" alt="'+d.name+'"><div><small>Opción '+(index+1)+'</small><strong>'+d.name+'</strong><span>'+d.brand+' · '+money(d.price)+'</span></div><button data-remove="'+d.id+'" type="button" aria-label="Quitar '+d.name+'">×</button></div>'
    ).join('')+(remaining?'<div class="drawer-slot">'+icon('plus')+' Puedes agregar '+remaining+' más</div>':''):
    '<div class="drawer-empty">Selecciona productos para comparar</div>';
  $('#openCompare').disabled=list.length<2;
  $('#openCompare').innerHTML=list.length<2?icon('plus')+' Elige mínimo 2':icon('compare')+' Comparar ahora';
}function showComparePage(){const list=state.compare.map(id=>devices.find(d=>d.id===id)).filter(Boolean); if(list.length<2)return; hideAll(); $('#comparePage').classList.remove('hidden'); const keys=[...new Set(list.flatMap(d=>Object.keys(d.specs)))]; const rows=[[`${icon('star')} Puntuación`,...list.map(d=>`${d.score} puntos`)],['Precio',...list.map(d=>money(d.price))],['Marca',...list.map(d=>d.brand)],['Año',...list.map(d=>d.year)],[`${icon('palette')} Colores`,...list.map(d=>join(d.colors))],[`${icon('chip')} Procesador / modelo`,...list.map(d=>join(d.processorVersions||d.versions))],[`${icon('drive')} RAM / batería`,...list.map(d=>join(d.ramVersions||d.batteryVersions))],[`${icon('drive')} Almacenamiento`,...list.map(d=>join(d.storageVersions))],...keys.map(k=>[`${specIcon(k)} ${k}`,...list.map(d=>d.specs[k]||'—')]),[`${icon('check')} Ventajas`,...list.map(d=>d.pros.join(' · '))],[`${icon('alert')} Puntos a considerar`,...list.map(d=>d.cons.join(' · '))],['Recomendado para',...list.map(d=>d.recommended)]]; $('#comparePageContent').innerHTML=`<div class="compare-summary">${list.map(d=>`<article><img src="${d.image}" alt="${d.name}"><div><span>${d.brand}</span><h3>${d.name}</h3><p>${money(d.price)}</p></div></article>`).join('')}</div><div class="compare-table-wrap"><table class="compare-table"><thead><tr><th>Especificación</th>${list.map(d=>`<th><div class="compare-head"><img src="${d.image}" alt="${d.name}"><strong>${d.name}</strong><span>${money(d.price)}</span></div></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>i?`<td>${c}</td>`:`<th>${c}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`; state.lastView='compare'; window.scrollTo({top:0,behavior:'smooth'});}
function route(){const h=location.hash.replace('#',''); if(h==='laptops')showCategory('laptops'); else if(h==='audifonos')showCategory('audifonos'); else if(h==='celulares')showCategory('telefonos'); else showHome();}
renderNews();renderDrawer();route();window.addEventListener('hashchange',route);
document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]'); if(cat){showCategory(cat.dataset.category)} const card=e.target.closest('[data-product]'); if(card && !e.target.closest('button')) showDetail(card.dataset.product); if(e.target.dataset.details) showDetail(e.target.dataset.details); if(e.target.dataset.compare) addCompare(e.target.dataset.compare); if(e.target.dataset.remove) removeCompare(e.target.dataset.remove); if(e.target.id==='openCompare') showComparePage(); if(e.target.id==='drawerToggle') $('#compareDrawer').classList.toggle('collapsed'); if(e.target.id==='backToCatalog') showCategory(state.category); if(e.target.id==='backFromCompare') route();});
['searchInput','brandFilter','yearFilter','featureFilter','priceRange'].forEach(id=>{document.getElementById(id).addEventListener('input',()=>{updatePriceLabel();renderProducts();});document.getElementById(id).addEventListener('change',()=>{updatePriceLabel();renderProducts();});});
$('#clearFilters').addEventListener('click',()=>{setupFilters();renderProducts();}); $('#themeBtn').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';$('#themeBtn').textContent=dark?'☾':'☀';});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
